src/router.js
src/views/Stats.vue

Ajoute une page `/stats` minimaliste

---

.github/workflows/docker.yml
README.md

À chaque nouveau tag Git.
Workflow :
```bash
$ npm version minor
$ git push --tags
```

Publication sur Docker Hub

---

src/views/Home.vue

one commit was missing in previous PR

removed start up detat wording, bold on argent public = code public

---

docs/ign.md

Pour que les données correspondent à "toutes les exploitations qui ont au moins une parcelle en bio".
Auparavant, c'était juste "toutes les parcelles bio".
refs #11

Documentation de l'export IGN

---

src/api/user.js
src/components/Login.vue
src/components/Profile.vue
src/main.js
src/store.js
src/store/modules/user.js
src/views/Map.vue

Ainsi, en rechargeant une page, l'utilisateur·ice retrouve son état de connexion.
Une personne connectée le reste jusqu'à la durée d'expiration du token, c'est-à-dire une journée.

Charge les données utilisateurs avec l'application

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/App.vue
src/components/AboutMenu.vue
src/components/HomeNavbar.vue
src/components/Navbar.vue
src/main.js
src/router.js
src/views/Changelog.vue
src/views/Map.vue
src/views/Stats.vue
vue.config.js

Il n'y a ainsi pas de dépendance client supplémentaire, la transformation se fait lors du build.
Le changelog est un moyen léger d'engager la curiosité des utilisateur·ices de l'application, et nous, de constituer le contenu du "service fait" au fil de l'eau.

Ajout d'un journal de nouveautés

---

README.md
docs/api.md
nginx.conf

C'est un <abbr title="Proof of concept">PoC</abbr> en vue de s'intégrer avec Alpes-Controle.
Elle doit répondre à ces questions :
- comment fonctionne l'identification, et comment obtenir un jeton ?
- quels sont les actions à disposition ?
- à quoi ressemble une sortie ?
- comment vérifier que ça a bien fonctionné ?
---

Documentation technique de l'API CartoBio

---

package-lock.json
package.json
src/assets/styles/index.js
src/assets/styles/old.json
src/assets/styles/ortho-vecto.json
src/assets/styles/vector.json
src/components/ParcelDetailsPopup.vue
src/views/Map.vue
vue.config.js

Affiche les informations cadastrales au survol d'une parcelle

---

src/views/Map.vue

Et inverse au passage les couches Opérateur avec les couches anonymes

Remplace l'icône "œil" par un toggle

---

src/components/AgriItem.vue
src/views/AgriList.vue

Et supprime le popup de confirmation.

Affichage conditionnel du bouton de parcelles

---

src/views/Stats.vue

Affiche le nombre d'OC qui utilisent l'API

---

src/components/Geosearch.vue
src/components/Map/SearchSidebar.vue
src/components/ParcelsList.vue
src/components/Profile.vue
src/store.js
src/views/Map.vue

Panneau latéral de recherche par ville/exploitation

---

src/components/Geosearch.vue
src/components/Map/SearchSidebar.vue
src/components/ParcelsList.vue
src/components/ParcelsListPreview.vue
src/views/Map.vue

Recherche sur un nom d'exploitation

---

src/assets/styles/cartobio.json
src/components/Geosearch.vue
src/components/Map/SearchSidebar.vue
src/store/modules/user.js
src/views/Map.vue

Affichage des Opérateurs sur la carte en mode Cluster

---

src/components/ParcelDetailsPopup.vue
src/views/Map.vue

Je n'ai pas implémenté la ligne grisée, car on ne gère pas l'information "nous n'avons pas les informations pour l'année en cours".
Ça ajoute un peu de boulot, qui peut se faire à part.

Nouvelle popup d'historique de parcelle

---

README.md
bin/export
src/workers/shapefile.js

Pour le fun : affiche le temps total d'export à la fin.

Élimination des doublons et écriture simultanée des .geojson et .shp

---

package-lock.json
package.json
src/components/Forms/OfflineLazyAutocomplete.vue
src/components/Prototypes/ParcelsAutoComplete.vue
src/components/Prototypes/PlotRow.vue
src/modules/codes-cultures/xml-dossier.js

Import PAC quasi instantané

---

package-lock.json
package.json
src/cadastre.js
src/cadastre.test.js
src/components/Forms/OfflineLazyAutocomplete.vue
src/components/Prototypes/ParcelsAutoComplete.vue
src/components/Prototypes/PlotRow.vue
src/main.js
src/plugins/vuetify.js

Et ajout de tests unitaires illustrant les cas pris en charge.

Parsing laxiste des références cadastrales

---

package-lock.json
package.json
src/components/Prototypes/ParcelsAutoComplete.vue
src/components/Prototypes/PlotRow.vue
src/modules/codes-cultures/xml-dossier.js

Import des parcelles Telepac

---

src/workers/shapefile.js

Exporte 3 champs supplémentaires :

---

.dockerignore
.github/workflows/docker.yml
Dockerfile
netlify.toml
nginx.conf
src/router.js
src/workers/shapefile.js

Cf. [Vue Router History Mode](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations).

Configure Nginx en mode Catch-All

---

src/pages/index.vue

je propose de retirer cette phrase qui est redondante en attendant de revoir tout ce paragraphe

Supprime phrase repetition

---

src/components/MainFooter.vue

Je ne vois pas trop ce que je fais car je travaille pas en local, faut que je m'en occupe ça sera plus simple. N'hésite pas à modifier et/ou nettoyer

Ajoute ligne "merci" + !
